"""Canonical CLI command inventory for the AQ transport surface."""

from __future__ import annotations

SURFACE_COMMANDS: tuple[tuple[str, ...], ...] = (
    ("whoami",),
    ("actor", "create"),
    ("actor", "list"),
    ("actor", "revoke"),
    ("actor", "grant"),
    ("actor", "revoke-cap"),
    ("key", "rotate"),
    ("project", "create"),
    ("project", "list"),
    ("project", "get"),
    ("project", "update"),
    ("project", "archive"),
    ("pipeline", "create"),
    ("pipeline", "list"),
    ("pipeline", "get"),
    ("pipeline", "update"),
    ("pipeline", "cancel"),
    ("job", "create"),
    ("job", "list"),
    ("job", "get"),
    ("job", "update"),
    ("claim",),
    ("release",),
    ("submit",),
    ("approve",),
    ("reject",),
    ("escrow", "unlock"),
    ("job", "reset"),
    ("job", "comment"),
    ("task-type", "register"),
    ("task-type", "list"),
    ("task-type", "get"),
    ("task-type", "update"),
    ("decision", "create"),
    ("decision", "list"),
    ("decision", "get"),
    ("decision", "supersede"),
    ("decision", "link"),
    ("learning", "submit"),
    ("learning", "list"),
    ("learning", "get"),
    ("learning", "search"),
    ("learning", "promote"),
    ("learning", "supersede"),
    ("learning", "expire"),
    ("learning", "edit"),
    ("graph", "neighborhood"),
    ("graph", "traverse"),
    ("surface", "search"),
    ("packet",),
    ("policy", "load"),
    ("policy", "list"),
    ("policy", "get"),
    ("policy", "attach"),
    ("run", "list"),
    ("run", "get"),
    ("audit",),
    ("artifact", "attach"),
    ("artifact", "list"),
    ("artifact", "get"),
    ("health",),
    ("stats",),
    ("setup",),
)

VISIBLE_GROUPS: tuple[str, ...] = (
    "actor",
    "project",
    "pipeline",
    "job",
    "task-type",
    "decision",
    "learning",
    "graph",
    "policy",
    "run",
    "artifact",
    "admin",
)

